import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex bg-[#00111C]">
          <div className="w-1/2 h-screen flex justify-center pt-24">
            <Navbar />
          </div>
          <div className="w-1/2 h-screen flex justify-center items-center">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
