import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <div className="fixed bg-[#00111C] w-[400px] h-screen flex px-10 items-center">
            <Navbar />
          </div>
          <div className="bg-[#fff] w-full h-screen ml-[400px] p-10">{children}</div>
        </div>
      </body>
    </html>
  );
}
